### ISSUE TITLE
Need a fully 200% scaled version for HiDPI.

### ISSUE THREAD

**Issue by wdhwg001** [somini/Pixelvision2#68]
Currently Steam doesn't support DPI scaling, and it seems won't be fixed in a significant period of time.

So the only way is to disable steam.exe's DPI scaling and make everything scale to 200% using skins.

Any wish to save retina displays?

Ps: The browser page can be scaled by adding css3 transforms in webkit.css.

``` css
body {
-webkit-transform: scale3d(2.0, 2.0, 1);
transform: scale3d(2.0, 2.0, 1);
transform-origin: 50% 0%;
-webkit-transform-origin: 50% 0%;
}
```

It's buggy, but it might be the only way.(`zoom: 2` does not work.)
